export const BTN_TYPE = {
  search: '查询',
  reset: '重置',
  add: '新增',
  upload: '导入',
  download: '导出',
  edit: '编辑',
  delete: '删除',
  view: '查看',
  save: '保存',
  back: '返回',
  // eslint-disable-next-line no-dupe-keys
  formDownload: '下载',
  preview: '预览',
  addCompare: '对比',
  addKey: '添加键值',
  filter: '筛选',
  close: '关闭',
  addmenu: '新增子项',
  addrole: '配置角色',
  configure: '配置菜单',
  bindDevice: '绑定设备',
  pass: '审核通过',
  reject: '审核不通过',
  apply: '提交',
  disabled: '禁用',
  dispreview: '不可预览',
  serviceIndexConfig: '服务水平指标配置',
};

export const BTN_ICON_TYPE = {
  [BTN_TYPE.search]: 'solar:magnifer-linear',
  [BTN_TYPE.reset]: 'material-symbols:sync-outline',
  [BTN_TYPE.add]: 'material-symbols:create-new-folder-outline-sharp',
  [BTN_TYPE.upload]: 'material-symbols:drive-folder-upload-outline',
  [BTN_TYPE.download]: 'material-symbols:cloud-download-outline',
  [BTN_TYPE.edit]: 'material-symbols:edit-note',
  [BTN_TYPE.delete]: 'material-symbols:delete-outline',
  [BTN_TYPE.view]: 'material-symbols:visibility',
  [BTN_TYPE.back]: 'material-symbols:arrow-back-ios-new-rounded',
  [BTN_TYPE.reset]: 'material-symbols:refresh',
  [BTN_TYPE.formDownload]: 'material-symbols:cloud-download-outline',
  [BTN_TYPE.preview]: 'material-symbols:visibility-outline',
  [BTN_TYPE.dispreview]: 'material-symbols:visibility-off-outline',
  [BTN_TYPE.addCompare]: 'material-symbols:docs-add-on',
  [BTN_TYPE.filter]: 'material-symbols:filter-alt-sharp',
  [BTN_TYPE.close]: 'mdi-close',
  [BTN_TYPE.addKey]: 'material-symbols:border-color-outline',
  [BTN_TYPE.addmenu]: 'material-symbols:edit-note',
  [BTN_TYPE.addrole]: 'material-symbols:border-color-outline',
  [BTN_TYPE.configure]: 'material-symbols:edit-note',
  [BTN_TYPE.bindDevice]: 'material-symbols:edit-note',
  [BTN_TYPE.pass]: 'mdi:account-check-outline',
  [BTN_TYPE.reject]: 'mdi:progress-close',
  [BTN_TYPE.apply]: 'mdi:account-multiple-check-outline',
  [BTN_TYPE.disabled]: 'material-symbols:edit-note',
  [BTN_TYPE.serviceIndexConfig]: 'material-symbols:rule-settings',
};
